### ISSUE TITLE
How to change color of float button?

### ISSUE THREAD

**Issue by rokity** [salte-io/paper-fab-menu#2]
I need to change the color of float button, how can I do it?

**Comment by nick-woodward** [comment]
Hey @rokity thanks for the submission! 
I've address our lack of documentation regarding this on the [docs](http://salte-io.github.io/paper-fab-menu/components/paper-fab-menu/demo/index.html)!

**You can style the parent and child FABs independently by doing the following:**
```html
<style is="custom-style">
  .color {
    --paper-fab-background: #536DFE;
    --paper-fab-keyboard-focus-background: #3A54E5;
  }

  .color paper-fab {
    --paper-fab-background: #673AB7;
    --paper-fab-keyboard-focus-background: #4E219E;
  }
</style>
<paper-fab-menu class="color" use-hover>
  <paper-fab mini icon="book"></paper-fab>
  <paper-fab mini icon="favorite"></paper-fab>
</paper-fab-menu>
```

[Here's also a live demo](https://jsbin.com/vimeluvafi/edit?html,output)

**Comment by rokity** [comment]
Sorry I didn't see it in [docs](http://salte-io.github.io/paper-fab-menu/components/paper-fab-menu/demo/index.html) .
Thank you for the help !!

**Comment by nick-woodward** [comment]
@rokity You're fine, I just added it to the documentation due to this ticket.

Closing since the issue has been resolved.
